Frontend for package page
openteamsinc/Score-Site pull request #9
Opened 2024-08-06 13:14 UTC by rajaFlutter

Fixed #2

2024-08-06 15:13 UTC, siddheshghadi751 requested changes

2024-08-06 15:13 UTC, siddheshghadi751 commented on src/app/page.tsx
> +                </button>
Add homepage URL here

2024-08-06 15:13 UTC, siddheshghadi751 commented on src/app/page.tsx
> +                </button>
add source URL here

2024-08-06 15:22 UTC, srossross requested changes
can you please fix the linter warnings?

2024-08-06 15:25 UTC, siddheshghadi751 commented
> can you please fix the linter warnings?

linter warning is already fixed now

2024-08-06 20:42 UTC, srossross commented
You have fixed the errors, but I'm still seeing the warnings:

<img width="509" alt="image" src="https://github.com/user-attachments/assets/9d8d2928-0a62-4e24-9330-a5d260930e3c">

https://medium.com/@dobinshin/how-to-use-eslint-plugin-tailwindcss-9b3aba12e5f5

Classnames Order:

    * Automatically sorts Tailwind CSS classes in a consistent order.
    * Enhances code readability.
    * Simplifies resolving merge conflicts.

2024-08-07 14:15 UTC, siddheshghadi751 approved these changes

2024-08-07 14:15 UTC, merged